name: Actions workflow
on: [push]

jobs:
  run-javascript:
    runs-on: windows-latest
    steps:
      - name: Simple js action 
        uses: https://github.com/macagua/example.java.helloworld.git@master
        
