name: Actions workflow
on: [push]

jobs:
  run-javascript:
    runs-on: windows-latest
    steps:
      - name: Simple js action 
        uses: actions/hello-world-javascript-action@v1.1
        with:
           who-to-greet: 'Prasath Kumar'
      - name: List Files
        run:  |
            pwd
            ls
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE

