name: Actions workflow
on: [push]
  # repository_dispatch:
    # type: [object]
  # schedule:
  # - cron: "0/5 * * * *"
  # - cron: "0-5 * * * *"
  

jobs:
  run-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run:  |
          pwd
          ls 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Simple js action 
        uses: actions/hello-world-javascript-action@v1.1
        with:
           who-to-greet: 'Prasath Kumar'
      

