name: Actions workflow
on: [push]

jobs:
  run-javascript:
    runs-on: windows-latest
    steps:
        # - name: Simple js action 
        # uses: macagua/example.java.helloworld@master
      - name: List Files
        run:
            pwd
            ls
