name: Actions workflow
on: [push]

jobs:
  run-javascript:
    runs-on: windows-latest
    steps:
      - name: Simple js action 
        uses: actions/hello-world-javascript-action@master
      - name: List Files
        run:  |
            pwd
            ls
