name: Shell Commands
on: 
  push:
    branches:    
      - main
    # - 'features/*'  matches features/featureA
    # - 'features/**'  matches features/featureA/Aa
    # - '!features/featureA'

  pull_request:
      types: [opened , reopened , closed ]

  # branches-ignore:    

  # tags:
    # -v2*

  # paths:
    # -'**.js'

jobs:
  shell-comman:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello Worlds"
   
      - name: Python shell
        run:  |
          import platform
          print
          (platform.processor())
        shell: python
  
  bash-comman:
    runs-on: windows-latest
    needs: ["shell-comman"]
    steps:
      - name: Powershell
        run: Get-Location
      - name: bash
        run: pwd
        shell: bash          
